[package]
name = "svg2web-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

description = "WASM bindings for svg2web"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
svg2web-core = { path = "../svg2web-core" }
wasm-bindgen = "=0.2.87"
wasm-bindgen-futures = "=0.4.37"
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = "=0.6.0"
serde_json.workspace = true
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "=0.3.37"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
