[package]
name = "svg2web-cache"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
svg2web-core = { path = "../svg2web-core" }
sled = { workspace = true, optional = true }
lru = { workspace = true, optional = true }
tokio.workspace = true
sha2.workspace = true

[features]
default = ["disk", "memory"]
disk = ["dep:sled"]
memory = ["dep:lru"]
