[package]
name = "svg2web-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "svg2web"
path = "src/main.rs"

[dependencies]
svg2web-core = { path = "../svg2web-core" }
svg2web-generator = { path = "../svg2web-generator" }
svg2web-cache = { path = "../svg2web-cache" }
clap.workspace = true
anyhow.workspace = true
tokio.workspace = true
env_logger.workspace = true
